### PR TITLE
Avoid warnings by removing 'static' from templates that currently are unused

### PR DESCRIPTION
**Pull request by mstorsjo**
This fixes warnings like these:

../src/MICmnLLDBDebugSessionInfo.cpp:877:17: warning: unused function 'GetBreakOrWatchPointAddress<lldb::SBBreakpoint>' [-Wunused-function]
lldb::SBAddress GetBreakOrWatchPointAddress(lldb::SBTarget &vrTarget,
                ^
../src/MICmnLLDBDebugSessionInfo.cpp:884:17: warning: unused function 'GetBreakOrWatchPointAddress<lldb::SBWatchpoint>' [-Wunused-function]
lldb::SBAddress GetBreakOrWatchPointAddress(lldb::SBTarget &vrTarget,
                ^

Alternative they could be removed altogether.

### CODE REVIEW

**Comment by tkrasnukha** [comment]
Could you, please, remove the whole declaration and replace the template specializations with the regular overloads?

**Comment by mstorsjo** [comment]
> Could you, please, remove the whole declaration and replace the template specializations with the regular overloads?

Ok, updated that way, I think.

They're still unused though, and now they are non-static functions. If I would keep `static` on each of the overloads, the compiler would warn that they're unused still though.

**Comment by tkrasnukha** [comment]
Really, looks like this code was committed mistakenly and should be removed. Thank you for catching that!

**Comment by mstorsjo** [comment]
> Really, looks like this code was committed mistakenly and should be removed. Thank you for catching that!

Ok, updated the patch to remove those functions altogether.

**Pull request merged**
