### PR TITLE
Link libraries from the LLVM_LIBRARY_DIRS location

### PR DESCRIPTION
**Pull request by Teemperor**

### CODE REVIEW

**Comment by Teemperor** [comment]
@tkrasnukha this is working for both static/shared LLVM libs.

**Comment by tkrasnukha** [comment]
We have to use `find_library` for LLVMSupport to obtain a correct absolute path to the library (in the case when we have different installations on the machine).

**Comment by tkrasnukha** [comment]
Also, neither this nor #29 works on Windows yet...

**Comment by Teemperor** [comment]
Now we're using find_library for LLVMSupport as a fallback.

Not sure what to do about Windows as I still haven't set up any Windows development env... Feel free to file issues for any Windows build errors.

**Comment by tkrasnukha** [comment]
It seems, static LLVMSupport requires `-lcurses`

**Comment by tkrasnukha** [comment]
It requires LLVMDemangle now, but I'd add something like this to avoid future problems:

```cmake
set(LLVM_DEPS "")

if (NOT libllvm)
  #find LLVMSupport
  #find Curses
  set_property(LLVMSupportDeps GLOBAL PROPERTY LLVMBUILD_LIB_DEPS_LLVMSupport)
  foreach(dependency ${LLVMSupportDeps})
    find_library(lib ${dependency} HINTS ${LLVM_LIBRARY_DIRS})
    list(APPEND LLVM_DEPS ${lib})
  endforeach()
  
  list(APPEND LLVM_DEPS ${CURSES_LIBRARIES} ${LLVM_PTHREAD_LIB})
endif()

target_link_libraries(lldb-mi ${liblldb} ${libllvm} ${LLVM_DEPS})
```

**Comment by tkrasnukha** [comment]
Updated #29 with this, seems like it works)

**Pull request closed without merging**
