### PR TITLE
Make the curses dependency optional

### PR DESCRIPTION
**Pull request by mstorsjo**
lldb-mi doesn't seem to use curses directly at all - this apparently
only is needed as a potential transitive dependency of lldb. Also,
as long as liblldb is linked dyanmically (which always is the case?),
lldb-mi shouldn't need to explicitly link against it at all.

Also, if curses was used by lldb itself, it should be available (and
be found), and if lldb was configured to not use curses, lldb-mi
should work fine without it as well.

### CODE REVIEW

**Comment by tkrasnukha** [comment]
`curses` is an llvmSupport's dependency. I think we can check `LLVM_ENABLE_TERMINFO` to decide whether we need it.

**Comment by mstorsjo** [comment]
> `curses` is an llvmSupport's dependency.

Ok, I see - and this is only invoked when LLVMSupport is being linked statically - so then it does makse sense for the cases where curses actually is used by LLVMSupport.

> I think we can check `LLVM_ENABLE_TERMINFO` to decide whether we need it.

That sounds like a good idea. Can you draft a patch for it?

**Comment by mstorsjo** [comment]
> > I think we can check `LLVM_ENABLE_TERMINFO` to decide whether we need it.
> 
> That sounds like a good idea. Can you draft a patch for it?

Actually it's a bit more of an issue than that... LLVM can pick up the terminfo library from a number of different names, see https://github.com/llvm/llvm-project/blob/master/llvm/cmake/config-ix.cmake#L178. In a lot of my configurations, I have `LLVM_ENABLE_TERMINFO` set to 1, but I don't have curses available (as it ended up picking libtinfo.so instead of curses). The `TERMINFO_LIB` that LLVM ended up using isn't exposed in LLVMConfig.cmake, but we can at least check a similar list of libraries. Updating the pull request accordingly.

**Comment by tkrasnukha** [comment]
To not break support of at least the latest LLVM release, we should also test that our platform is not windows.

**Comment by mstorsjo** [comment]
Done, amended the commit to include a `AND NOT WIN32` condition.

**Comment by tkrasnukha** [comment]
Seem great, thank you! I'll merge it as soon as the CI build finishes.

**Comment by mstorsjo** [comment]
Actually, it turns out that this doesn't work with older version of LLVM (neither with release 10 or 11); the handling of `LLVM_ENABLE_TERMINFO` was changed in the master branch (past the 11 release branch). Before, it looked like this: https://github.com/llvm/llvm-project/blob/release/11.x/llvm/cmake/config-ix.cmake#L142-L155

So `LLVM_ENABLE_TERMINFO` only is a hint that terminfo would be nice to have, but whether it actually was enabled or not, only is stored in `HAVE_TERMINFO` (which isn't exposed in LLVMConfig).

Would it be safest to demote this `find_library` to optional? If a terminfo lib was used for LLVM, it should ideally exist also while building lldb-mi (and the `find_library` should, ideally, find it). If it was used while building LLVM but is removed before building lldb-mi, we're screwed anyway. If it does exist (and it was found when building LLVM), but isn't found when building lldb-mi (due to incorrect cmake search paths or whatnot), we get a bit more link time error instead of a slightly clearer cmake error though...

**Pull request merged**
