### PR TITLE
Migrate form Travis to Github Actions

### PR DESCRIPTION
**Pull request by tkrasnukha**
The CI has been broken for a while. There are 2 reasons:  travis-ci.org was replaced by travis-ci.com, and 'mikkeloscar/arch-travis' stopped working and become unsupported. That prompted me to migrate our CI to github actions.

The workflow takes now about 5-6 minutes and runs on Ubuntu, MacOS and Windows (except tests, they are skipped on Windows currently).

### CODE REVIEW

**Comment by tkrasnukha** [comment]
@Teemperor please, disable "continuous-integration/travis-ci" since it doesn't work and doesn't allow to accept PRs (I don't have access to the project settings).

**Comment by Teemperor** [comment]
Huh, weird, I thought I made you admin. Sorry for that!

**Comment by Teemperor** [comment]
Removed travis-ci. Thanks for taking care of that! I also added you as a project admin.

**Review by Teemperor — APPROVED** [review]

**Comment by tkrasnukha** [comment]
Thank you!

**Pull request merged**
