### PR TITLE
Link libraries from the LLVM_LIBRARY_DIRS location

### LINKED ISSUE #8: How to avoid -lLLVM error
I have a clang compiler installed on my system, but am trying to use the clang that I've built myself, configuring lldb-mi with:

export CC=/opt/lzlabs/gcc-9.2.0/bin/gcc
export CXX=/opt/lzlabs/gcc-9.2.0/bin/g++
#export CXX="/opt/lzlabs/gcc-9.2.0/bin/g++ -std=c++14"

export LD_LIBRARY_PATH=/opt/lzlabs/gcc-9.2.0/lib64:/opt/lzlabs/lldb/lib64

export PATH=/opt/lzlabs/gcc-9.2.0/bin:/home/pjoot/gdb/bin:/opt/lzlabs/lldb/bin:$PATH

cmake \
   -DCMAKE_PREFIX_PATH=/opt/lzlabs/lldb \
   -DBUILD_SHARED_LIBS=true \
   -DCMAKE_BUILD_TYPE=Release \
   -DCMAKE_SHARED_LINKER_FLAGS='-B/home/pjoot/gdb/bin' \
   -DCMAKE_EXE_LINKER_FLAGS='-B/home/pjoot/gdb/bin' \
   -DLLVM_LIBDIR_SUFFIX=64 \
   -DCMAKE_INSTALL_RPATH=/opt/lzlabs/gcc-9.2.0/lib64:/opt/lzlabs/lldb/lib64 \
   -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE \
   -GNinja ../lldb-mi

I end up with an error when lldb-mi is linked as my build.ninja tries to use -lLLVM (which curiously doesn't seem to exist in either the llvm that is part of the old clang-3.8 that is installed on my system, nor in my just built llvm+lldb (trunk))

I was able to work around that by changing the build.ninja reference to -lLLVM into `llvm-config --libs` (that's backquotes mangled by markup into highlighted text)

Is there a proper way to do this, without hacking the generated build.ninja?

### PR DESCRIPTION
**Pull request by tkrasnukha**
This commit fixes runtime error
```
: CommandLine Error: Option 'disable-symbolication' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

Linking only the LLVMSupport from the same location also led to this error (i.e. an another LLVM shared library was loaded at runtime?)

Should also fix #8

### CODE REVIEW

**Comment by Teemperor** [comment]
LGTM, not sure why Travis is not getting this to run, but I guess that's just the node being really slow?

**Comment by tkrasnukha** [comment]
Yes, I think so, because the first build was successful (build [#156](https://travis-ci.org/lldb-tools/lldb-mi/builds/611811743)).

**Comment by Teemperor** [comment]
The llvm-inst file should be smaller now, so maybe that makes this work better.

**Comment by Teemperor** [comment]
Does #31 fix your use case?

**Comment by Teemperor** [comment]
LGTM, thanks for getting this to work!

**Pull request merged**
