### PR TITLE
Tweak Jan Kratochvil's "Simplify linked libraries: LLVMSupport -> LLVM"

### PR DESCRIPTION
**Pull request by peeterjoot**
change.

Don't hardcode LLVM (or LLVMSupport), but use: `llvm-config --libs`

### CODE REVIEW

**Comment by tkrasnukha** [comment]
Closes #8 

@Teemperor, could you take a look, please?

**Comment by Teemperor** [comment]
CMake's execute_process should probably be used instead of backticks (which will most likely not work on any system that doesn't have a build system that just invokes a shell with backtick support).

Also just calling llvm-config will end up looking in PATH, but we probably should see if we can get that path from the AddLLVM.cmake file (or maybe the library list itself which would be even better).

**Comment by peeterjoot** [comment]
@Teemperor What is the syntax for the execute_process.  I tried:

--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -74,4 +74,4 @@ add_executable(lldb-mi
   MIUtilVariant.cpp
 )
 
-target_link_libraries(lldb-mi lldb `llvm-config --libs` pthread)
+target_link_libraries(lldb-mi lldb execute_process(llvm-config --libs) pthread)

but this results in a build error:

riant.cpp.o  -o src/lldb-mi -L/opt/lzlabs/lldb/lib64 -Wl,-rpath,/opt/lzlabs/gcc-9.2.0/lib64:/opt/lzlabs/lldb/lib64 -llldb -lexecute_process -l( -lllvm-config --libs -l) -lpthread && :
/bin/sh: -c: line 0: syntax error near unexpected token `('

**Comment by tkrasnukha** [comment]
Should be something like
`execute_process(COMMAND "llvm-config --libs" OUTPUT_VARIABLE libs)`

and then `libs` should contain the command output.

**Comment by peeterjoot** [comment]
@tkrasnukha Okay, I tried that, but if I use execute_process, it picks up llvm-config from /usr/bin/ and not from my $PATH.  Is there a way to get execute_process to use $PATH?

**Comment by tkrasnukha** [comment]
`find_path(llvm_config_path "llvm-config" PATHS ENV PATH)`  ?

**Comment by tkrasnukha** [comment]
I'm sorry, `find_program(llvm_config_path "llvm-config")` should work as expected.

**Comment by peeterjoot** [comment]
> I'm sorry, `find_program(llvm_config_path "llvm-config")` should work as expected.

Okay, getting closer.  With:

    find_program(llvm_config_program "llvm-config" PATHS ENV PATH)
    message(${llvm_config_program})
    
    execute_process(
      COMMAND "${llvm_config_program} --libs"
      OUTPUT_VARIABLE libs)
    message(${libs})
    
    target_link_libraries(lldb-mi lldb ${libs} pthread)

my path for llvm-config is found (according to message + cmake --trace), but my execute_process output somehow ends up empty:

    /home/pjoot/chirag/lldb-mi/src/CMakeLists.txt(77):  find_program(llvm_config_program llvm-config PATHS ENV PATH )
    /home/pjoot/chirag/lldb-mi/src/CMakeLists.txt(78):  message(${llvm_config_program} )
    /opt/lzlabs/lldb/bin/llvm-config
    /home/pjoot/chirag/lldb-mi/src/CMakeLists.txt(80):  execute_process(COMMAND ${llvm_config_program} --libs OUTPUT_VARIABLE libs )
    /home/pjoot/chirag/lldb-mi/src/CMakeLists.txt(83):  message(${libs} )
    CMake Error at src/CMakeLists.txt:83 (message):
      message called with incorrect number of arguments

**Comment by Teemperor** [comment]
We really shouldn't use PATH at all. Otherwise it's possible (and likely) that you can use a different llvm-config than the one LLVM_DIR points to. We should get the libraries or llvm-config from the CMake where we get the other options from.

**Comment by peeterjoot** [comment]
> We really shouldn't use PATH at all. Otherwise it's possible (and likely) that you can use a different llvm-config than the one LLVM_DIR points to. We should get the libraries or llvm-config from the CMake where we get the other options from.

Are you suggesting something like:

target_link_libraries(lldb-mi lldb ${LLVM_FOO} pthread)

where LLVM_FOO is one of the TARGET related variables in LLVMConfig.cmake, or LLVMExports.cmake?

**Comment by Teemperor** [comment]
It's also fine to ask llvm-config from the LLVM_DIR about the libraries, but getting the information from some the CMake configuration in LLVM_DIR would be preferred. I don't have time to do this myself now, but I added a macOS image to the CI that tests building with a downloaded LLDB install prefix that checks if this works.

**Comment by Teemperor** [comment]
I believe #31 should fix your problem?

**Comment by tkrasnukha** [comment]
I'm closing this PR as the problem seems to be fixed with #29 and #31.

**Pull request closed without merging**
